### ISSUE TITLE
Adding STEIM2 to encoding option

### ISSUE THREAD

**Issue by biondiettore** [crotwell/simplemseed#1]
It would be great to have encoding capabilities on MSEED3. In particular, have STEIM2 encoding. Thanks!

**Comment by crotwell** [comment]
I just pushed in steim1 and steim2 encoding, but have only done very minimal testing. Can you grab the source and run some tests to see ifthe compression looks ok? 

I can push out a release once you give the ok.

**Comment by crotwell** [comment]
in v0.3.0
